dependencies:
  # -<organisation/repo>@<version>
  - smartcontractkit/chainlink@2.13.0

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@2.13.0'

dotenv: .env

networks:
  Sepolia:
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: TRUE
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419' 
    verify: FALSE
  development:
    verify: FALSE
  ganache-local:
    verify: FALSE
wallets:
  from_key: ${PRIVATE_KEY}